//
//  File.swift
//  
//
//  Created by Alexander Cyon on 2021-07-22.
//

import Foundation

public enum Creature: Int, Equatable {
    case peasant = 1,
         archer,
         ranger,
         pikeman,
         veteranPikeman,
         swordsman,
         masterSwordsman,
         cavalry,
         champion,
         paladin,
         crusader,
         goblin,
         orc,
         orcChief,
         wolf,
         ogre,
         ogreLord,
         troll,
         warTroll,
         cyclops,
         sprite,
         dwarf,
         battleDwarf,
         elf,
         grandElf,
         druid,
         greaterDruid,
         unicorn,
         phoenix,
         centaur,
         gargoyle,
         griffin,
         minotaur,
         minotaurKing,
         hydra,
         greenDragon,
         redDragon,
         blackDragon,
         halfling,
         boar,
         ironGolem,
         steelGolem,
         roc,
         mage,
         archmage,
         giant,
         titan,
         skeleton,
         zombie,
         mutantZombie,
         mummy,
         royalMummy,
         vampire,
         vampireLord,
         lich,
         powerLich,
         boneDragon,
         rogue,
         nomad,
         ghost,
         genie,
         medusa,
         earthElemental,
         airElemental,
         fireElemental,
         waterElemental
}
